### ISSUE TITLE
We don't support cucumber version 6

### ISSUE THREAD

**Issue by smartm0use** [ahasall/angular-cucumber-demo#1]
Hello, I have follow your guide but I get the following error:

**E/launcher - Error: Error: We don't support cucumber version 6**

Should I open an issue on [protractor-cucumber-framework](https://github.com/protractor-cucumber-framework/protractor-cucumber-framework) repository?

**Comment by ahasall** [comment]
I will have a look at it and come back to you.

**Comment by ahasall** [comment]
Yes you should open an issue in their repository or downgrade your version of cucumber:
```bash
npm install --save-dev cucumber@5
```

**Comment by smartm0use** [comment]
Yes, I solved downgrading it. Now I'm going to open an issue there.
Thank you.

**Comment by ahasall** [comment]
You're welcome 😉.
